### ISSUE TITLE
doesn't seem to work anymore. Plans for an update?

### ISSUE THREAD

**Issue by Troyciv** [pschlette/memrise2anki-extension#1]
this addon doesn't seem to work anymore. I don't know what they changes in their api, do have any plans to update this addon?

```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "/home/user/.local/share/Anki2/addons/Memrise_Course_Importer/importer.py", line 146, in run
    course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
  File "/home/user/.local/share/Anki2/addons/Memrise_Course_Importer/memrise.py", line 752, in loadCourse
    return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
  File "/home/user/.local/share/Anki2/addons/Memrise_Course_Importer/memrise.py", line 568, in loadCourse
    level = self.loadLevel(course, levelIndex)
  File "/home/user/.local/share/Anki2/addons/Memrise_Course_Importer/memrise.py", line 623, in loadLevel
    if levelData["success"] == False:
KeyError: 'success'
```

**Comment by pschlette** [comment]
Nope, sorry! Haven't used Memrise in ages - didn't even know it was still around. PRs welcome, but I'm not sure how much value the existing code has by now.

**Comment by nicolasmaia** [comment]
I suspect it may have to do with a recent Anki update.

@pcuinty you might wanna check https://github.com/wilddom/memrise2anki-extension
